# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
     from: debian:latest
     run: 
       -apt update && apt upgrade -y
       -apt install git curl python3-pip ffmpeg -y
       -pip3 install -U pip
       -curl -sL https://deb.nodesource.com/setup_15.x | bash -
       -apt-get install -y nodejs
       -npm i -g npm
       -mkdir /app/
workdir: /app/
copy: . /app/
run: pip3 install -U -r requirements.txt
cmd: python3 main.py
